name: xpunlocks
version: 1.0.0
api-version: '1.19'
main: me.steinlbert.main
description: This plugin does so much stuff it can't be contained!
author: steinlbert
commands:
  xpunlocks:
    usage: /<command>
    description: Shows the Version of xpunlocks
  xpunlocks-help:
    usage: /<command>
    description: Shows usefull stuff in German
  xpunlocks-help-en:
    usage: /<command>
    description: Shows usefull stuff in English
  xpunlocks-config:
    usage: /<command>
    description: Shows the whole Config
  xpunlocks-resetxp:
    usage: /<command>
    description: reset the Lvl of the plyer to zerro
  xpunlocks-rewards:
    usage: /<command>
    description: Shows the rewards or classes of this Plugins
  xpunlocks-kit:
    usage: /<command>
    description: Shows the kits usage /xpunlocks-kit *int*